### PR TITLE
Interval plot in plotly

### PR DESCRIPTION
**Pull request by jiwanheo**
Here's the code I used to generate the plots. `myPlot` should return a list of plotly plots you can cycle through

```
library(pander)
library(clinUtils)

data(dataSDTMCDISCP01)
dataSDTM <- dataSDTMCDISCP01
labelVarsSDTM <- attr(dataSDTM, "labelVars")
dataAE <- dataSDTM$AE

# sort severities
dataAE[, "AESEV"] <- factor(dataAE[, "AESEV"], levels = c("MILD", "MODERATE", "SEVERE"))

myPlot <- subjectProfileIntervalPlot(
  data = dataAE,
  paramVar = "AETERM",
  timeStartVar = "AESTDY",
  timeEndVar = "AEENDY",
  colorVar = "AESEV",
  labelVars = labelVarsSDTM,
  title = "Adverse events"
)

```

### CODE REVIEW

**Comment by skgithub14** [comment]
@jiwanheo I'm still looking at this but a few things come to mind:

1. Need to add plotly to the DESCRIPTION file
2. I don't think we want to eliminate the ggplot functionality but rather add the plotly functionality in addition to ggplot. Because we may contribute back to open source and some users may not want plotly, we should design the functionality so they can choose. So there are a few ways we could do this, one being we create new functions that are specifically for plotly versions or we could create a new argument for the functions such as plotly = TRUE that would switch the outputs from ggplot to plotly. What do you think?

**Comment by skgithub14** [comment]
@jiwanheo I finished looking at the code and have a few more comments, mostly regarding generalization. 

We need to generalize this function so it can be used to plot any domain, not just AEs. For example, we are planning on using the interval plot for the CM and EX domains too. If we do open source this in the end, then other users may want additional domains supported.

There was one call that factored the column AETERM that needs to be generalized.

The tool tip contents need to be generalized and customizable. Not only will the tool tips change domain to domain, but depending on the study and user, they may want different variables listed on the tool tips. So we should design it where the user can either supply the tooltip html code as an argument or at least supply the variable names and labels they want included.

We also need a shape legend to describe what the squares versus triangles are.

**Comment by jiwanheo** [comment]
@skgithub14 

- Added plotly & forcats to DESCRIPTION
- Added `plotly = FALSE` argument to toggle between ggplot/plotly
- Removed hardcode

Comments on the 2 issues that I didn't do

## Custom tooltip

I removed all the hardcode, except "Status" for shape variable name (Complete, missing start, missing end). I don't think it's a good idea to be as flexible as possible. This column is calculated in the function, with 2 columns being used as status, with `is.na` being the only determinator. 

If we decide to let people change it to whatever they want (for example, a case_when to handle multiple shapes), that'll add more complexity to the code for each column we want to keep in mind. I suggest we keep it simple for now, use it for AE first, then accomodate more as needed.

## Shape legend

So plotly doesn't provide a shape legend, and it's one of those things that you have to hack around to force it in there. I can try a little more, but I'm running out of ideas. For now, the on-hover tooltip has this information

image

**Comment by skgithub14** [comment]
@jiwanheo progress looks good. Regarding the shapes, that's not a big deal. What I was referring two is the content of the hover information. This will change from domain to domain and is a requirement per Kai. I think we can leave the 3 default values you have in there as is but there should be a way to provide a named vector of column names and column labels that are programmatically added to the tool tip's hover info.

Regarding the legend, I'm running into the same issue for the line plots. Not sure how to resolve it yet. But I'm thinking we might just have to create a fake legend, which is just a separate image that sites next to the chart. I don't like it but not sure how else I can differentiate shapes and colors in the line plots.

**Comment by jiwanheo** [comment]
@skgithub14 

Ok, just a note, I layer 2 separate plotly traces for start and end point dots. The information for shapes is stored in two separate columns `timeStartStatus` and `timeEndStatus`. 

I can pass in a named vector `plotly_hover_text <- c("Status" = "timeStartStatus", "Severity" = "AESEV")`, and do something like this.

image

But notice we're using "timeStartStatus". This won't work for the end points, because we need to separately pass in timeEndStatus.

Yes, we can pass in `list(start = c("Status" = "timeStartStatus"), End = c("Status", "timeEndStatus"), common = c("Severity" = "AESEV")`, but I feel customizing to this degree opens a can of worms of user requests for customization, and feels unnatural.

At the very least, I think it'll be good to see what kind of hover information we'd actually be using at SAR, before going down this route

**Comment by skgithub14** [comment]
@jiwanheo I'm been working on this issue for the line plots and I came up with this function that allows a somewhat customizeable hovertemplate that's flexible enough to accommodate any domains it will support.

I'm looking at the ctmonitor requirements document for this feature and it looks like the following tool tips are required for the interval plots:

ADAE:
- date
- SOC/PT
- severity
- grade
- SAE status
- action taken
- On going (Y/N)

ADCM:
- date
- route
- dose
- frequency
- indication
- On going (Y/N)

ADEX:
- date/time
- visit
- dose
- body weight
- reason if missed dose, reduced dose, or suspended dose

```
hover_tmp <- function(title, 
                        xLab, 
                        paramValueVar, 
                        colorLab = NULL, 
                        colorVal = NULL, 
                        shapeLab = NULL, 
                        shapeVal = NULL,
                        visit = NULL,
                        date = NULL,
                        lln = NULL,
                        uln = NULL,
                        grade = NULL,
                        alert = NULL) {
    
    # title (parameter), value, and study day
    ht <- paste0(
      '<b>', title, '</b><br><br>',
      '<i>', paramValueVar, '</i>: %{y}<br>',
      '<i>', xLab, '</i>: %{x}<br>'
    )
    
    ## additional timing variables
    # visit
    if (!is.null(visit)) {
      ht <- paste0(
        ht,
        '<i>Visit</i>: ', visit, '<br>'
      )
    }
    
    # date
    if (!is.null(date)) {
      ht <- paste0(
        ht,
        '<i>Date</i>: ', date, '<br>'
      )
    }
    
    ## additional aesthetic variables
    # color
    if (!is.null(colorLab) & !is.null(colorVal)) {
      ht <- paste0(
        ht,
        '<i>', colorLab, '</i>: ', colorVal, '<br>'
      )
    }
    
    # shape
    if (!is.null(shapeLab) & !is.null(shapeVal)) {
      ht <- paste0(
        ht,
        '<i>', shapeLab, '</i>: ', shapeVal, '<br>'
      )
    }
    
    # ranges
    if (!is.null(lln) & !is.null(uln)) {
      ht <- paste0(
        ht,
        '<i>ULN</i>: ', uln, '<br>',
        '<i>LLN</i>: ', lln, '<br>'
      )
    }
    
    ## value interpretation variables
    # grade
    if (!is.null(grade)) {
      if (!is.na(grade) & grade != "") {
        ht <- paste0(
          ht,
          '<i>Grade</i>: ', grade, '<br>'
        )
      }
    }
    
    # alert
    if (!is.null(alert)) {
      if (!is.na(alert) & alert != "") {
        ht <- paste0(
          ht,
          '<i>Alert</i>: ', alert, '<br>'
        )
      }
    }
    
    ht <- paste0(ht, '<extra></extra>')
    return(ht)
  }

# implementation
plotly::plot_ly(
        .,
        x = ~.data[[timeVar]],
        y = ~yVar
      ) %>%
        plotly::add_trace(
          type = "scatter",
          mode = "markers",
          symbol = ~shapeVarSymbol,
          marker = list(
            color = colorPalette[which(names(colorPalette) == unique(.data[[colorVar]]))],
            size = shapeSize,
            opacity = alpha
          ),
          legendgroup = ~yVar,
          showlegend = FALSE,
          hovertemplate = hover_tmp(
            title = unique(.data$paramFacetVar), 
            xLab = xLab, 
            paramValueVar = paramValueVar, 
            colorLab = colorLab, 
            colorVal = unique(.data[[colorVar]]), 
            shapeLab = shapeLab, 
            shapeVal = .data[[shapeVar]],
            visit = .data[[visitVar]],
            date = .data[[dateVar]],
            lln = .data[[paramValueRangeVar[1]]],
            uln = .data[[paramValueRangeVar[2]]]
          )
        )
```

**Comment by jiwanheo** [comment]
@skgithub14 

I've added the `plotly_hover_text` argument, where user can specify a named vector, where if provided, plotly hover will include
this information, in form of `<b>Name</b>: value`

For example, this code, will result in hover text of

```
library(pander)
library(clinUtils)

data(dataSDTMCDISCP01)
dataSDTM <- dataSDTMCDISCP01
labelVarsSDTM <- attr(dataSDTM, "labelVars")
dataAE <- dataSDTM$AE

# sort severities
dataAE[, "AESEV"] <- factor(dataAE[, "AESEV"], levels = c("MILD", "MODERATE", "SEVERE"))

myPlot <- subjectProfileIntervalPlot(
  data = dataAE,
  paramVar = "AETERM",
  timeStartVar = "AESTDY",
  timeEndVar = "AEENDY",
  colorVar = "AESEV",
  labelVars = labelVarsSDTM,
  title = "Adverse events",
  plotly = TRUE,
  plotly_hover_text = c("Subject ID" = "USUBJID", "Study ID" = "STUDYID")
)
```

image

**Review by skgithub14 — APPROVED** [review]
Looks good, may come back to do paging later

**Pull request merged**
