### PR TITLE
Fully integrated versions of line, interval, and text plots with plotly outputs

### PR DESCRIPTION
**Pull request by skgithub14**
@jiwanheo for testing and example code see these files in /patientProfilesVis/tests/testthat/

- test_plotlyIntervalPlot.R
- test_plotlyLinePlot.R
- test_plotlyEventPlot.R

### CODE REVIEW

**Comment by jiwanheo** [comment]
lineplot legend turns on/off in chunks. is this intended?

image

**Comment by jiwanheo** [comment]
Same with interval chart, but with this one, i don't mind it

image

**Comment by skgithub14** [comment]
> lineplot legend turns on/off in chunks. is this intended?
> 
> image

Yes it's intended. I figured the user would typically want to be able to quickly remove chunks instead of having to individually click off all the of same shape values and/or color values manually. I think we can try it this way and if the users don't like it, we can change it back. In the final shiny app module there may also be accompanying filter inputs that would work with the chart so the user can have more granular control too.

**Comment by skgithub14** [comment]
> Same with interval chart, but with this one, i don't mind it
> 
> image

Yes this is also intended

**Review by jiwanheo — APPROVED** [review]

**Pull request merged**
